version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.9

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Clean and Build
          command: mvn -f unittest/pom.xml clean package -DskipTests

  unit_test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn -f unittest/pom.xml test -Dtest=com.mayab.quality.unittest.service.UserServiceTest

  integration_test:
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calidad2024
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Wait for MySQL to Start
          command: |
            for i in $(seq 1 30); do
              nc -z localhost 3306 && echo "MySQL is up!" && break
              echo "Waiting for MySQL..."
              sleep 1
            done
            if ! nc -z localhost 3306; then
              echo "MySQL failed to start." && exit 1
            fi
      - run:
          name: Run Integration Tests
          command: mvn -f unittest/pom.xml failsafe:integration-test -Dtest=com.mayab.quality.integration.UserServiceTest

  selenium_test:
    docker: 
      - image: cimg/openjdk:17.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Run Selenium Functional Tests
          command: mvn -f unittest/pom.xml verify -Dtest=com.mayab.quality.functional.CRUDSeleniumTest

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - unit_test:
          requires:
            - build-and-test
      - integration_test:
          requires:
            - unit_test
      - selenium_test:
          requires:
            - integration_test
